# Project: cpp_templates
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = SwappingNum.o
LINKOBJ  = SwappingNum.o
LIBS     = -L"C:/Programs/Dev-Cpp/MinGW64/lib" -L"C:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Programs/Dev-Cpp/MinGW64/include" -I"C:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Programs/Dev-Cpp/MinGW64/include" -I"C:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = cpp_templates.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

SwappingNum.o: SwappingNum.cpp
	$(CPP) -c SwappingNum.cpp -o SwappingNum.o $(CXXFLAGS)
