# Project: Bank
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = BankAccount.o
LINKOBJ  = BankAccount.o
LIBS     = -L"C:/Programs/Dev-Cpp/MinGW64/lib" -L"C:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Programs/Dev-Cpp/MinGW64/include" -I"C:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Programs/Dev-Cpp/MinGW64/include" -I"C:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Bank.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

BankAccount.o: BankAccount.cpp
	$(CPP) -c BankAccount.cpp -o BankAccount.o $(CXXFLAGS)
